export const LOAD_MODEL_LIST = 'LOAD_MODEL_LIST';

export const BRAND_LIST = 'BRAND_LIST';

export const LOAD_MORE_MODELS = 'LOAD_MORE_MODELS';

export const IS_LOADER_COMPLETED = 'IS_LOADER_COMPLETED';

export const IS_LOADER_INITIAL = 'IS_LOADER_INITIAL';

export const LOAD_ALL_MODEL_LIST = 'LOAD_ALL_MODEL_LIST';

export const CALCULATE_COUNT_MODEL = 'CALCULATE_COUNT_MODEL';

export const CALCULATE_CURRENT_COUNT_MODEL = 'CALCULATE_CURRENT_COUNT_MODEL';